### ISSUE TITLE
USER STORY: Like recipes

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/theRecipeCollective#10]
As a **user** I can **like recipes** so that **share my opinion about it**

# Acceptance Cirteria: 
* Acceptance Criteria 1: A visible "like" button for each recipe
* Acceptance Criteria 2: Ability to like a recipe only once per user account
* Acceptance Criteria 3: A counter displaying the number of likes for each recipe
* Acceptance Criteria 4: Log in is needed to be able to like.

# Tasks
- [ ] Add a "like" button to the recipe page
- [ ] Implement a counter to show the total amount of likes. 
- [ ] Implement a check to varify if the user is logged in before allowing them to like the recipe. If not, prompt them to log in.

**Comment by SandraBergstrom** [comment]
I have decided to change the feature from "must-have" to "should-have" as I would like to add a "[save to favorites](https://github.com/SandraBergstrom/theRecipeCollective/issues/10)" option instead. I believe that in a recipe sharing site, users would prefer to save the recipes they like instead of just liking them.
