### ISSUE TITLE
USER STORY: Comment on recipe

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/theRecipeCollective#11]
As a **user** I can **comment on a recipe** so that **share my thoughts and suggestions**

# Acceptance Cirteria: 
* Acceptance Criteria 1: A visible field to "Add a Comment" is present on the recipe page.
* Acceptance Criteria 2: The comment will automatically add the current user and the date.
* Acceptance Criteria 3: The comment is added to the recipe page with the username and date included.
* Acceptance Criteria 4: The user can edit or delete their own comments.

# Tasks
- [x] Add a "Add a Comment" text field with button (form) to the recipe page.
- [x] Add username and date automatically and let the user know they are commenting as them.
- [x] Add the ability to display comments on the recipe page with the username and date included.
- [ ] Implement functionality to allow users to edit or delete their own comments.
