### ISSUE TITLE
USER STORY: User profile page

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/theRecipeCollective#12]
As a **user** I can **go to my profile page** so that **I can see my saved recipes and personal information**

# Acceptance Cirteria: 
* Acceptance Criteria 1: A visible button or link to access the profile page.
* Acceptance Criteria 2: The profile page displays the user's saved recipes.
* Acceptance Criteria 3: The profile page displays the user's personal information, such as name, email, food relation and country.
* Acceptance Criteria 4: Visible form and update button on profile page.

# Tasks
- [x] Create a new page for the profile and add a link to access it.
- [x] Implement functionality to retrieve and display the user's saved recipes on the profile page.
- [x] Implement functionality to retrieve and display the user's personal information on the profile page.
- [x] Add possibility to update profile.
