### ISSUE TITLE
USER STORY: Adjust serving size

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/theRecipeCollective#20]
As a **user** I can **adjust the servings for a recipe** so that I **can get an updated list of ingredients to match the new serving size**

# Acceptance Criteria: 
* Acceptance Criteria 1: The updated list of ingredients should be calculated based on the adjusted serving size.
* Acceptance Criteria 2: 

# Tasks
- [ ] Add a "Serving Size" field to the recipe form.
- [ ] Calculate the updated ingredient list based on the adjusted serving size.
- [ ] Add a button to adjust serving size on the recipe page.
