### ISSUE TITLE
USER STORY: Create an account

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/theRecipeCollective#3]
As a **user** I can **create an account** so that I **can save my recipes**

# Acceptance Cirteria: 
* Acceptance Criteria 1: Visible button to press "Create and account"
* Acceptance Criteria 2:  Registration form with fields for user name, email address, password, food relation and country.  
* Acceptance Criteria 3: email validation so the user is uniqe. Appropriate error message if not.
* Acceptance Criteria 4: Re-directed to a Sign in page.
* Acceptance Criteria 5: validation that all fields are filled in and also max_lenght, min_lenght on name. 

# Tasks
- [x] Create a view for the registration form that will handle GET and POST requests.
- [x] Create a form in Django that includes fields for username, email address, password, food relation and country.
- [x] Add validation to the form.
- [x] Extend the User model with a new model to store more data about the user. 
- [x] Redirect the user to log in after successful registration. 
- [x] Flash message to further clarify successful registration.

**Comment by SandraBergstrom** [comment]
Tasks:
- done
- will add food relation and country when model extension of user is done. 
- done
- will work on this when login/logout is OK
- Not sure about the redirection to log in is needed. Will check after login/logout is working OK
- done

**Comment by SandraBergstrom** [comment]
Redirect fixed
