### ISSUE TITLE
USER STORY: Login/Logout of account

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/theRecipeCollective#4]
As a user I can login/logout of my account so that I can access my saved recipes securely.

# Acceptance Criteria: 
* Acceptance Criteria 1: Visible button to press "Log in" and "Log out" when appropriate.
* Acceptance Criteria 2:  Login form with fields for username and password.
* Acceptance Criteria 3: Re-directed to a home page that shows all recipes after successful login. Redirected to logged out page upon logout.

Tasks

# Tasks
- [x] Add "Log in" and "Log out" buttons to appropriate pages.
- [x] Create login form with username and password fields.
- [x] Re-direct to recipe home page
- [x] Implement login/logout functionality in views.py and urls.py.
