### ISSUE TITLE
USER STORY: Add recipe

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/theRecipeCollective#5]
As a **user** I can **add a new recipe** so that **can share it with others and save it for myself**

# Acceptance Cirteria: 
* Acceptance Criteria 1: Visible button to press "Add recipe"
* Acceptance Criteria 2: Recipe form with fields for recipe title, ingredients, instructions and image upload.
* Acceptance Criteria 3: After successful submission, the recipe is visible to all users on the platform.

# Tasks
- [x] Create "Add recipe" button on homepage
- [x] Create recipe form with appropriate fields
- [x] Implement image upload functionality for recipe form

**Comment by SandraBergstrom** [comment]
Image upload is not working.

**Comment by SandraBergstrom** [comment]
[Fixed](https://github.com/SandraBergstrom/theRecipeCollective/issues/5#issuecomment-1527424073)
