### ISSUE TITLE
USER STORY: Delete recipe

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/theRecipeCollective#8]
As a **user** I can **delete my own recipe** so that **remove them if wanted**

# Acceptance Cirteria: 
* Acceptance Criteria 1: A "Delete" button is visible on the user's own recipe page
* Acceptance Criteria 2: Clicking on the "Delete" button prompts a confirmation dialog box to prevent accidental deletion
* Acceptance Criteria 3: The recipe is deleted from the database and is no longer visible to other users or the owner

# Tasks
- [x]  Add a "Delete" button on the user's own recipe page
- [x] Implement a confirmation dialog box when the "Delete" button is clicked
- [x] Implement the deletion of the recipe from the database
